In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [2]:
kanto_temp, kanto_rainfall, kanto_humidity = 73, 67, 43

In [3]:
kanto_apple_yeild = kanto_temp*w1 +kanto_rainfall*w2 + kanto_humidity*w3
print(kanto_apple_yeild)

56.8


In [4]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 138, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [5]:
weights = [w1, w2, w3]

In [6]:
result = 0
for x, y in zip(kanto, weights):
    result += x*y
print(result)

56.8


In [7]:
def crop_yeild(region, weights):
    result=0
    for x, y in zip(region, weights):
        result += x*y
    print(result)

In [8]:
%time
crop_yeild(kanto, weights)

CPU times: total: 0 ns
Wall time: 0 ns
56.8


# Starting with Numpy

In [9]:
import numpy as np

In [10]:
weights_np = np.array([w1, w2, w3])

In [11]:
kanto_np = np.array(kanto)

In [12]:
kanto_np

array([73, 67, 43])

In [13]:
print(kanto_np.shape)
print(weights_np.shape)

(3,)
(3,)


In [14]:
print(type(weights_np))
print(type(kanto_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [15]:
kanto_np * weights_np

array([21.9, 13.4, 21.5])

In [16]:
np.dot(kanto_np, weights_np)

56.8

In [17]:
np.sum(kanto_np * weights_np)

56.8

# Comparison bitween Numpy & List

In [18]:
# List
arr1 = list(range(100000))
arr2 = list(range(100000, 200000))

# Numpy
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [19]:
%%time
result =0
for x, y in zip(arr1, arr2):
    result += x*y
print(result)

833323333350000
CPU times: total: 93.8 ms
Wall time: 85 ms


In [20]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


893678192

In [21]:
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]])

In [22]:
climate_data.shape

(5, 3)

In [23]:
type(climate_data)

numpy.ndarray

In [24]:
len(climate_data)

5

In [25]:
np.max(climate_data)

134

In [26]:
weights_np.shape

(3,)

In [27]:
np.dot(kanto, weights_np)

56.8

In [28]:
np.sum(kanto * weights_np)

56.8

In [29]:
weights_np

array([0.3, 0.2, 0.5])

In [30]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [31]:
np.matmul(climate_data, weights_np)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [32]:
climate_data @ weights_np

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [33]:
weights_np.shape

(3,)

In [34]:
weights_np.reshape(-1,3)

array([[0.3, 0.2, 0.5]])

In [35]:
weights_np.shape

(3,)

In [36]:
weights_np.reshape(3,)

array([0.3, 0.2, 0.5])

In [37]:
weights_np.shape

(3,)

In [39]:
climate_data = np.genfromtxt('data/climate.txt', delimiter=',', skip_header=True)

In [40]:
climate_data.shape

(10000, 3)

In [41]:
weights_np

array([0.3, 0.2, 0.5])

In [42]:
weights_np.shape

(3,)

In [43]:
climate_data *  weights_np

array([[ 7.5, 15.2, 49.5],
       [11.7, 13. , 35. ],
       [17.7,  9. , 38.5],
       ...,
       [29.7, 12.4, 29. ],
       [21. , 14.2, 45.5],
       [27.6,  7.8, 38. ]])

In [44]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [45]:
np.sum(climate_data*weights_np, axis=1)

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [46]:
np.sum(climate_data*weights_np, axis=0)

array([179524.2, 120348.6, 300533. ])

In [47]:
climate_data@weights_np

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [48]:
yields = climate_data @ weights_np

In [49]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [50]:
yields.shape

(10000,)

In [51]:
climate_conc_result = np.concatenate((climate_data, yields.reshape(-1, 1)), axis=1)

In [52]:
climate_conc_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [53]:
yields.shape

(10000,)

In [54]:
yields.reshape(10000, 1).shape

(10000, 1)

In [55]:
yields.shape

(10000,)

In [56]:
np.savetxt('data/climate_conc_result.txt', climate_conc_result, fmt='%.2f', header = 'temperature, humidity, rainfall, yields', comments='')

# Broadcasting

In [57]:
arr1 = np.array([1, 2, 3])

In [58]:
arr2 = np.array([[[1, 2],
                  [3, 4],
                  [5, 6]],
                 [[7, 8],
                  [9, 10],
                  [11, 12]]])

In [59]:
arr2.shape

(2, 3, 2)

In [60]:
# Shape
# arr1 -       x 2 broadcasted to 2 x 3 x 2
# arr2 - 2 x 3 x 2

In [61]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,) (2,3,2) 

In [62]:
arr1 * arr2.reshape(-1, 1)

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18],
       [ 7, 14, 21],
       [ 8, 16, 24],
       [ 9, 18, 27],
       [10, 20, 30],
       [11, 22, 33],
       [12, 24, 36]])

In [63]:
arr2_reshaped = arr2.reshape(-1, 4)

In [64]:
arr2_reshaped.shape

(3, 4)